// <auto-generated />
using System;
using LesGo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LesGo.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("LesGo.Models.Ride", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RideTime")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("LesGo.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Rideid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Rideid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LesGo.Models.User", b =>
                {
                    b.HasOne("LesGo.Models.Ride", null)
                        .WithMany("Riders")
                        .HasForeignKey("Rideid");
                });

            modelBuilder.Entity("LesGo.Models.Ride", b =>
                {
                    b.Navigation("Riders");
                });
#pragma warning restore 612, 618
        }
    }
}
